sudo: required
language: python
services:
  - docker
python:
  - "2.7"

before_install:
  - pip install testinfra
  - docker build -t wdijkerman/consul .
  - docker run -d --name consul -p 127.0.0.1:8500:8500 -p 127.0.0.1:8400:8400 -p 127.0.0.1:8300:8300 -p 127.0.0.1:8600:53/udp wdijkerman/consul -server -bootstrap -ui-dir /consul/ui
  - docker ps -a

script:
  - testinfra --connection=docker --hosts=consul

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push wdijkerman/consul;
    fi
