---

version: "2"

services:
  consul:
    image: wdijkerman/consul
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8500:8500"
#    volumes:
#      - ./config.json:/consul/config/consul.json
